theme: jekyll-theme-cayman
permalink: pretty
exclude: [README.md, vendor, Gemfile, Gemfile.lock]
title: "Mathsoc Wiki"
future: true

collections:
  modules:
    output: true
    permalink: /modules/:path/


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default" 
  -
    scope:
      path: "modules"
    values:
      type: "module-year"
      layout: "module-year"
